# MNIST Classifier

In this notebook you will create both, an mnist tabular dataset and a classifier.

## 1.- import the Operating System (os) module in python and any other library you need

In [43]:
import numpy as np
import pandas as pd
import random

import os
from tqdm import tqdm
from PIL import Image

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score

In [44]:
parent_dir = "Data"
    data = pd.DataFrame()
    for folder in os.listdir(parent_dir):

        print(folder)

        if folder == "train":
            for f in os.listdir(parent_dir+"/"+folder):

                class_data = np.zeros(  ( len(os.listdir(parent_dir+"/"+folder+"/"+f) ), 785) )
                print(class_data.shape)

                for i, img_name in enumerate(os.listdir(parent_dir+"/"+folder+"/"+f)):

                    img = Image.open(parent_dir+"/"+folder+"/"+f+"/"+img_name)
                    img_arr = np.array(img, dtype=int)
                    img_arr = img_arr.flatten()
                    class_data[i,:784] = img_arr
                    class_data[i,784] = int(f)

                class_data = pd.DataFrame(class_data)
                data = pd.concat([data, class_data])
                print(data.shape)

IndentationError: unexpected indent (<ipython-input-44-21ecff5f1027>, line 2)

## 2.- As you can see each class has its own folder (Do it only for train). 

    - Iterate folder by folder ( os.listdir() )
    - Inside each folder: 
        1.- Read the image
        2.- Reshape it into a flat array (784,)
        3.- Save the data into a pandas dataframe apending the column name as the class
    - Save the data into a CSV

    Note: if it takes to long try doing only 100 images per folder and the teacher for the CSV.

In [46]:
par_dir = r'C:\Users\User\Documents\GitHub\practice folders\module 4 (Feature engineering)\03.-image\data'
data= pd.DataFrame()
for folder in os.listdir(par_dir):
#print(folder)
 if folder== 'train':
    for f in os.listdir(par_dir+"/"+folder):
        class_data = np.zeros((len(os.listdir(par_dir+"/" +folder+"/"+f)),785))
        #print(class_data.shape)
        for i, img_name in enumerate(os.listdir(par_dir+"/" +folder+"/"+f)):
            img = Image.open(par_dir+"/" +folder+"/"+f+'/'+img_name)
            img_arr = np.array(img, dtype = int)
            img_arr=img_arr.flatten()
            class_data[i,:784]= img_arr
            class_data[i,784]= int(f)
        class_data=pd.DataFrame(class_data)
        data= pd.concat([data, class_data])
        print(data.shape)

#data =pd.DataFrame(class_data)

(4132, 785)
(8816, 785)
(12993, 785)
(17344, 785)
(21416, 785)
(25211, 785)
(29348, 785)
(33749, 785)
(37812, 785)
(42000, 785)

In [40]:
data.to_csv('mnist.csv')

## 3.- Load the CSV

In [41]:
df1= pd.read_csv('mnist.csv')
df1

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,775,776,777,778,779,780,781,782,783,784
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,4.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4183,4183,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
4184,4184,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
4185,4185,0.0,3.0,6.0,1.0,0.0,2.0,2.0,0.0,0.0,...,7.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,9.0
4186,4186,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
4187,4187,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0

## 4.- Create a dictionary of models (No preprocessing needed, it has already been done).
    
    Include both, tree models and mult models.

## 5.- Using either cross validation or stratification find out which is the best model
    - Base your code on the previous two days examples

## Optional: Can you rotate an image?